### ISSUE TITLE
Missing styles when service worker is running

### ISSUE THREAD

**Issue by JakeChampion** [AdaRoseEdwards/ada.is#3]
OS: OS X 10.10.3
Browser: Google Chrome Version 43.0.2357.132 (64-bit)
I've taken some screenshots of errors I have come across after activating the offline reading feature:

![screen shot 2015-07-08 at 10 01 02](https://cloud.githubusercontent.com/assets/1569131/8680042/9ddbfc9a-2a56-11e5-8c6d-e27603368649.png)

![screen shot 2015-07-14 at 18 25 53](https://cloud.githubusercontent.com/assets/1569131/8680049/ab774710-2a56-11e5-97de-937b69256a68.png)

It seems a soft-refresh fixes the issue.

**Comment by AdaRoseEdwards** [comment]
Thanks  for the heads up I was aware it occasionally happens, something similar I've seen is that occasionally on refresh you will get old data on a request even though that data should not be in the cache.
